sudo: required
dist: trusty

os: linux

language: c

compiler:
  - gcc

env:
  matrix:
    LUAROCKS_VERSION=2.4.2

addons:
  apt:
    packages:
        - lua5.1 lua5.1-dev git libssl-dev build-essential wget unzip

cache:
  apt: true
  directories:
  - download-cache

before_script:
  - wget -O- https://openresty.org/package/pubkey.gpg | sudo apt-key add -
  - echo "deb http://openresty.org/package/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install --no-install-recommends openresty openresty-resty -y
  - wget https://luarocks.org/releases/luarocks-${LUAROCKS_VERSION}.tar.gz
  - tar zxpf luarocks-${LUAROCKS_VERSION}.tar.gz
  - cd luarocks-${LUAROCKS_VERSION}
  - ./configure; sudo make bootstrap
  - sudo luarocks install lua-cjson
  - sudo luarocks install luaposix
  - sudo luarocks install https://raw.githubusercontent.com/jdesgats/telescope/master/rockspecs/telescope-scm-1.rockspec
  - sudo luarocks install luasocket
  - sudo luarocks install luasec
  - sudo luarocks install luacheck
  - cd ..
  - rm -fr luarocks-${LUAROCKS_VERSION}

script:
  - make test
